# Makefile.in generated by automake 1.16.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#
# $Id: Makefile.am 5036 2020-03-01 17:18:01Z chrfranke $
#




am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/smartmontools
pkgincludedir = $(includedir)/smartmontools
pkglibdir = $(libdir)/smartmontools
pkglibexecdir = $(libexecdir)/smartmontools
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-w64-mingw32
am__append_1 = -DSMARTMONTOOLS_DRIVEDBDIR='"$(drivedbdir)"'
#am__append_2 = -DSMARTMONTOOLS_SAVESTATES='"$(savestates)"'
#am__append_3 = -DSMARTMONTOOLS_ATTRIBUTELOG='"$(attributelog)"'
am__append_4 = -I$(srcdir)/os_win32
#am__append_5 = -I$(srcdir)/getopt -D_GETOPT_STANDALONE
am__append_6 = -I$(srcdir)/regex -D_REGEX_STANDALONE
sbin_PROGRAMS = smartctl$(EXEEXT) smartd$(EXEEXT)
am__append_7 = \
        os_win32/popen_win32.cpp \
        os_win32/popen.h

am__append_8 = smartctl_res.o
am__append_9 = smartctl_res.o
am__append_10 = \
        os_win32/daemon_win32.cpp \
        os_win32/daemon_win32.h \
        os_win32/popen_win32.cpp \
        os_win32/popen.h \
        os_win32/syslog_win32.cpp \
        os_win32/syslog.h

am__append_11 = smartd_res.o
am__append_12 = smartd_res.o
#am__append_13 = \
#        getopt/getopt.c \
#        getopt/getopt.h \
#        getopt/getopt1.c \
#        getopt/getopt_int.h \
#        getopt/bits/getopt_core.h \
#        getopt/bits/getopt_ext.h

#am__append_14 = \
#        getopt/getopt.c \
#        getopt/getopt.h \
#        getopt/getopt1.c \
#        getopt/getopt_int.h \
#        getopt/bits/getopt_core.h \
#        getopt/bits/getopt_ext.h

am__append_15 = \
        regex/regex.c \
        regex/regex.h \
        regex/regex_internal.h

am__append_16 = \
        regex/regex.c \
        regex/regex.h \
        regex/regex_internal.h


# Included by regex.c:
am__append_17 = \
        regex/regcomp.c \
        regex/regexec.c \
        regex/regex_internal.c

am__append_18 = \
        regex/regcomp.c \
        regex/regexec.c \
        regex/regex_internal.c

am__append_19 = \
        csmisas.h \
        os_win32/wmiquery.cpp \
        os_win32/wmiquery.h

am__append_20 = \
        csmisas.h \
        os_win32/wmiquery.cpp \
        os_win32/wmiquery.h

am__append_21 = -lole32 -loleaut32
am__append_22 = -lole32 -loleaut32
#am__append_23 = update-smart-drivedb.1m
am__append_24 = update-smart-drivedb.8
#am__append_25 = \
#        $(exedir_win32)/update-smart-drivedb.exe

am__append_26 = \
        $(exedir_win32)/drivedb.h

am__append_27 = \
        $(FILES_WIN32) \
        defadmin.manifest \
        distdir.mkdir \
        runcmda.exe runcmda_res.rc \
        runcmdu.exe runcmdu_res.rc \
        smartctl-nc.exe smartctl-nc.exe.tmp \
        smartctl_res.rc smartd_res.rc \
        syslogevt.h \
        syslogevt.rc syslogevt_*.bin \
        update-smart-drivedb.exe \
        wtssendmsg.exe wtssendmsg_res.rc

subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/pkg.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(top_srcdir)/configure \
	$(am__configure_deps) $(am__DIST_COMMON)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(sbindir)" "$(DESTDIR)$(examplesdir)" \
	"$(DESTDIR)$(sbindir)" "$(DESTDIR)$(smartdscriptdir)" \
	"$(DESTDIR)$(man5dir)" "$(DESTDIR)$(man8dir)" \
	"$(DESTDIR)$(docsdir)" "$(DESTDIR)$(drivedbdir)" \
	"$(DESTDIR)$(examplesdir)" "$(DESTDIR)$(initddir)" \
	"$(DESTDIR)$(sysconfdir)" "$(DESTDIR)$(systemdsystemunitdir)"
PROGRAMS = $(sbin_PROGRAMS)
am__smartctl_SOURCES_DIST = smartctl.cpp smartctl.h atacmdnames.cpp \
	atacmdnames.h atacmds.cpp atacmds.h ataidentify.cpp \
	ataidentify.h ataprint.cpp ataprint.h dev_ata_cmd_set.cpp \
	dev_ata_cmd_set.h dev_intelliprop.cpp dev_interface.cpp \
	dev_interface.h dev_jmb39x_raid.cpp dev_tunnelled.h drivedb.h \
	json.cpp json.h knowndrives.cpp knowndrives.h nvmecmds.cpp \
	nvmecmds.h nvmeprint.cpp nvmeprint.h scsicmds.cpp scsicmds.h \
	scsiata.cpp scsinvme.cpp scsiprint.cpp scsiprint.h \
	static_assert.h utility.cpp utility.h sg_unaligned.h \
	os_win32/popen_win32.cpp os_win32/popen.h getopt/getopt.c \
	getopt/getopt.h getopt/getopt1.c getopt/getopt_int.h \
	getopt/bits/getopt_core.h getopt/bits/getopt_ext.h \
	regex/regex.c regex/regex.h regex/regex_internal.h csmisas.h \
	os_win32/wmiquery.cpp os_win32/wmiquery.h
am__objects_1 = popen_win32.$(OBJEXT)
#am__objects_2 = getopt.$(OBJEXT) \
#	getopt1.$(OBJEXT)
am__objects_3 = regex.$(OBJEXT)
am__objects_4 = wmiquery.$(OBJEXT)
am_smartctl_OBJECTS = smartctl.$(OBJEXT) atacmdnames.$(OBJEXT) \
	atacmds.$(OBJEXT) ataidentify.$(OBJEXT) ataprint.$(OBJEXT) \
	dev_ata_cmd_set.$(OBJEXT) dev_intelliprop.$(OBJEXT) \
	dev_interface.$(OBJEXT) dev_jmb39x_raid.$(OBJEXT) \
	json.$(OBJEXT) knowndrives.$(OBJEXT) nvmecmds.$(OBJEXT) \
	nvmeprint.$(OBJEXT) scsicmds.$(OBJEXT) scsiata.$(OBJEXT) \
	scsinvme.$(OBJEXT) scsiprint.$(OBJEXT) utility.$(OBJEXT) \
	$(am__objects_1) $(am__objects_2) $(am__objects_3) \
	$(am__objects_4)
am__EXTRA_smartctl_SOURCES_DIST = os_darwin.cpp os_darwin.h \
	os_linux.cpp os_linux.h os_freebsd.cpp os_freebsd.h \
	os_netbsd.cpp os_netbsd.h os_openbsd.cpp os_openbsd.h \
	os_os2.cpp os_os2.h os_qnxnto.cpp os_qnxnto.h os_solaris.cpp \
	os_solaris.h os_win32.cpp os_generic.cpp os_generic.h \
	aacraid.h cciss.cpp cciss.h cissio_freebsd.h dev_areca.cpp \
	dev_areca.h dev_legacy.cpp linux_nvme_ioctl.h megaraid.h \
	regex/regcomp.c regex/regexec.c regex/regex_internal.c
smartctl_OBJECTS = $(am_smartctl_OBJECTS)
am__DEPENDENCIES_1 =
am__smartd_SOURCES_DIST = smartd.cpp atacmdnames.cpp atacmdnames.h \
	atacmds.cpp atacmds.h dev_ata_cmd_set.cpp dev_ata_cmd_set.h \
	dev_intelliprop.cpp dev_interface.cpp dev_interface.h \
	dev_jmb39x_raid.cpp dev_tunnelled.h drivedb.h knowndrives.cpp \
	knowndrives.h nvmecmds.cpp nvmecmds.h scsicmds.cpp scsicmds.h \
	scsiata.cpp scsinvme.cpp static_assert.h utility.cpp utility.h \
	sg_unaligned.h os_win32/daemon_win32.cpp \
	os_win32/daemon_win32.h os_win32/popen_win32.cpp \
	os_win32/popen.h os_win32/syslog_win32.cpp os_win32/syslog.h \
	getopt/getopt.c getopt/getopt.h getopt/getopt1.c \
	getopt/getopt_int.h getopt/bits/getopt_core.h \
	getopt/bits/getopt_ext.h regex/regex.c regex/regex.h \
	regex/regex_internal.h csmisas.h os_win32/wmiquery.cpp \
	os_win32/wmiquery.h
am__objects_5 = daemon_win32.$(OBJEXT) \
	popen_win32.$(OBJEXT) \
	syslog_win32.$(OBJEXT)
am_smartd_OBJECTS = smartd.$(OBJEXT) atacmdnames.$(OBJEXT) \
	atacmds.$(OBJEXT) dev_ata_cmd_set.$(OBJEXT) \
	dev_intelliprop.$(OBJEXT) dev_interface.$(OBJEXT) \
	dev_jmb39x_raid.$(OBJEXT) knowndrives.$(OBJEXT) \
	nvmecmds.$(OBJEXT) scsicmds.$(OBJEXT) scsiata.$(OBJEXT) \
	scsinvme.$(OBJEXT) utility.$(OBJEXT) $(am__objects_5) \
	$(am__objects_2) $(am__objects_3) $(am__objects_4)
am__EXTRA_smartd_SOURCES_DIST = os_darwin.cpp os_darwin.h os_linux.cpp \
	os_linux.h os_freebsd.cpp os_freebsd.h os_netbsd.cpp \
	os_netbsd.h os_openbsd.cpp os_openbsd.h os_os2.cpp os_os2.h \
	os_qnxnto.cpp os_qnxnto.h os_solaris.cpp os_solaris.h \
	os_win32.cpp os_generic.cpp os_generic.h aacraid.h cciss.cpp \
	cciss.h cissio_freebsd.h dev_areca.cpp dev_areca.h \
	dev_legacy.cpp linux_nvme_ioctl.h freebsd_nvme_ioctl.h \
	netbsd_nvme_ioctl.h megaraid.h regex/regcomp.c regex/regexec.c \
	regex/regex_internal.c
smartd_OBJECTS = $(am_smartd_OBJECTS)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
SCRIPTS = $(examples_SCRIPTS) $(sbin_SCRIPTS) $(smartdscript_SCRIPTS)
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__maybe_remake_depfiles = depfiles
am__depfiles_remade = ./$(DEPDIR)/atacmdnames.Po \
	./$(DEPDIR)/atacmds.Po ./$(DEPDIR)/ataidentify.Po \
	./$(DEPDIR)/ataprint.Po ./$(DEPDIR)/cciss.Po \
	./$(DEPDIR)/daemon_win32.Po ./$(DEPDIR)/dev_areca.Po \
	./$(DEPDIR)/dev_ata_cmd_set.Po ./$(DEPDIR)/dev_intelliprop.Po \
	./$(DEPDIR)/dev_interface.Po ./$(DEPDIR)/dev_jmb39x_raid.Po \
	./$(DEPDIR)/dev_legacy.Po ./$(DEPDIR)/getopt.Po \
	./$(DEPDIR)/getopt1.Po ./$(DEPDIR)/json.Po \
	./$(DEPDIR)/knowndrives.Po ./$(DEPDIR)/nvmecmds.Po \
	./$(DEPDIR)/nvmeprint.Po ./$(DEPDIR)/os_darwin.Po \
	./$(DEPDIR)/os_freebsd.Po ./$(DEPDIR)/os_generic.Po \
	./$(DEPDIR)/os_linux.Po ./$(DEPDIR)/os_netbsd.Po \
	./$(DEPDIR)/os_openbsd.Po ./$(DEPDIR)/os_os2.Po \
	./$(DEPDIR)/os_qnxnto.Po ./$(DEPDIR)/os_solaris.Po \
	./$(DEPDIR)/os_win32.Po ./$(DEPDIR)/popen_win32.Po \
	./$(DEPDIR)/regcomp.Po ./$(DEPDIR)/regex.Po \
	./$(DEPDIR)/regex_internal.Po ./$(DEPDIR)/regexec.Po \
	./$(DEPDIR)/scsiata.Po ./$(DEPDIR)/scsicmds.Po \
	./$(DEPDIR)/scsinvme.Po ./$(DEPDIR)/scsiprint.Po \
	./$(DEPDIR)/smartctl.Po ./$(DEPDIR)/smartd.Po \
	./$(DEPDIR)/syslog_win32.Po ./$(DEPDIR)/utility.Po \
	./$(DEPDIR)/wmiquery.Po
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX     " $@;
am__v_CXX_1 = 
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD   " $@;
am__v_CXXLD_1 = 
CCASCOMPILE = $(CCAS) $(AM_CCASFLAGS) $(CCASFLAGS)
AM_V_CCAS = $(am__v_CCAS_$(V))
am__v_CCAS_ = $(am__v_CCAS_$(AM_DEFAULT_VERBOSITY))
am__v_CCAS_0 = @echo "  CCAS    " $@;
am__v_CCAS_1 = 
SOURCES = $(smartctl_SOURCES) $(EXTRA_smartctl_SOURCES) \
	$(nodist_EXTRA_smartctl_SOURCES) $(smartd_SOURCES) \
	$(EXTRA_smartd_SOURCES) $(nodist_EXTRA_smartd_SOURCES)
DIST_SOURCES = $(am__smartctl_SOURCES_DIST) \
	$(am__EXTRA_smartctl_SOURCES_DIST) $(am__smartd_SOURCES_DIST) \
	$(am__EXTRA_smartd_SOURCES_DIST)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
man5dir = $(mandir)/man5
man8dir = $(mandir)/man8
NROFF = nroff
MANS = $(man_MANS)
DATA = $(docs_DATA) $(drivedb_DATA) $(examples_DATA) $(initd_DATA) \
	$(sysconf_DATA) $(systemdsystemunit_DATA)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/config.h.in AUTHORS \
	COPYING ChangeLog INSTALL NEWS README TODO compile \
	config.guess config.sub depcomp install-sh missing
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/tab/smartmontools-code/smartmontools/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
ASFLAGS = 
AUTOCONF = ${SHELL} /home/tab/smartmontools-code/smartmontools/missing autoconf
AUTOHEADER = ${SHELL} /home/tab/smartmontools-code/smartmontools/missing autoheader
AUTOMAKE = ${SHELL} /home/tab/smartmontools-code/smartmontools/missing automake-1.16
AWK = gawk
CAPNG_LDADD = 
CC = x86_64-w64-mingw32-gcc
CCAS = x86_64-w64-mingw32-gcc
CCASDEPMODE = depmode=gcc3
CCASFLAGS = -g -O2
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CXX = x86_64-w64-mingw32-g++
CXXCPP = x86_64-w64-mingw32-g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -D__USE_MINGW_ANSI_STDIO -g -O2 -Wall -W -Wformat=2 -fstack-protector-strong
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DRIVEDB_BRANCH = RELEASE_7_0_DRIVEDB
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = .exe
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = -static -Wl,--nxcompat,--tsaware -Wl,--dynamicbase,-pie,-emainCRTStartup,--high-entropy-va,--image-base,0x140000000
LIBOBJS = 
LIBS = 
LTLIBOBJS = 
MAINT = #
MAKEINFO = ${SHELL} /home/tab/smartmontools-code/smartmontools/missing makeinfo
MAKENSIS = 
MKDIR_P = /bin/mkdir -p
NM = x86_64-w64-mingw32-nm
OBJEXT = o
PACKAGE = smartmontools
PACKAGE_BUGREPORT = smartmontools-support@listi.jpberlin.de
PACKAGE_NAME = smartmontools
PACKAGE_STRING = smartmontools 7.2
PACKAGE_TARNAME = smartmontools
PACKAGE_URL = 
PACKAGE_VERSION = 7.2
PATH_SEPARATOR = :
PKG_CONFIG = 
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = 
SET_MAKE = 
SHELL = /bin/bash
STRIP = x86_64-w64-mingw32-strip
SYSTEMD_LDADD = 
VERSION = 7.2
WINDMC = x86_64-w64-mingw32-windmc
WINDRES = x86_64-w64-mingw32-windres
abs_builddir = /home/tab/smartmontools-code/smartmontools
abs_srcdir = /home/tab/smartmontools-code/smartmontools
abs_top_builddir = /home/tab/smartmontools-code/smartmontools
abs_top_srcdir = /home/tab/smartmontools-code/smartmontools
ac_ct_CC = 
ac_ct_CXX = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
attributelog = 
attributelogdir = 
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = x86_64-pc-linux-gnu
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
drivedbdir = ${datadir}/${PACKAGE}
dvidir = ${docdir}
exampledir = ${docdir}/examplescripts
exec_prefix = ${prefix}
gcc_have_attr_packed = yes
gnupg = gpg
host = x86_64-w64-mingw32
host_alias = x86_64-w64-mingw32
host_cpu = x86_64
host_os = mingw32
host_vendor = w64
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
initddir = 
initdfile = smartd.initd
install_sh = ${SHELL} /home/tab/smartmontools-code/smartmontools/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
os_deps = os_win32.o dev_areca.o
os_dltools = curl wget lynx svn
os_dnsdomainname = 
os_hostname = 'hostname' 'uname -n'
os_libs = 
os_mailer = mail
os_man_filter = Windows
os_nisdomainname = 'domainname'
os_win32_manifest = os_win32/default.manifest
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
releaseversion = ${PACKAGE}-${VERSION}
runstatedir = ${localstatedir}/run
savestates = 
savestatesdir = 
sbindir = ${exec_prefix}/sbin
scriptpath = /usr/local/bin:/usr/bin:/bin
sharedstatedir = ${prefix}/com
smartd_suffix = 
smartdplugindir = ${smartdscriptdir}/smartd_warning.d
smartdscriptdir = ${sysconfdir}
smartmontools_release_date = 2019-12-30
smartmontools_release_time = 15:00:11 UTC
srcdir = .
svn_deps = 
sysconfdir = ${prefix}/etc
systemdenvfile = 
systemdsystemunitdir = 
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
with_nvme_devicescan = yes
with_update_smart_drivedb = yes
ACLOCAL_AMFLAGS = -I m4

# Make sure .cpp takes precedence to avoid compiling old .c file
SUFFIXES = .cpp .c .s .o

# BUILD_INFO can be provided by package maintainers (see INSTALL file)
BUILD_INFO = "(local build)"
AM_CPPFLAGS = -DBUILD_INFO='$(BUILD_INFO)' \
	-DSMARTMONTOOLS_SYSCONFDIR='"$(sysconfdir)"' \
	-DSMARTMONTOOLS_SMARTDSCRIPTDIR='"$(smartdscriptdir)"' \
	$(am__append_1) $(am__append_2) $(am__append_3) \
	$(am__append_4) $(am__append_5) $(am__append_6)
#sbin_SCRIPTS = update-smart-drivedb
smartctl_SOURCES = smartctl.cpp smartctl.h atacmdnames.cpp \
	atacmdnames.h atacmds.cpp atacmds.h ataidentify.cpp \
	ataidentify.h ataprint.cpp ataprint.h dev_ata_cmd_set.cpp \
	dev_ata_cmd_set.h dev_intelliprop.cpp dev_interface.cpp \
	dev_interface.h dev_jmb39x_raid.cpp dev_tunnelled.h drivedb.h \
	json.cpp json.h knowndrives.cpp knowndrives.h nvmecmds.cpp \
	nvmecmds.h nvmeprint.cpp nvmeprint.h scsicmds.cpp scsicmds.h \
	scsiata.cpp scsinvme.cpp scsiprint.cpp scsiprint.h \
	static_assert.h utility.cpp utility.h sg_unaligned.h \
	$(am__append_7) $(am__append_13) $(am__append_15) \
	$(am__append_19)
smartctl_LDADD = $(os_deps) $(os_libs) $(am__append_8) \
	$(am__append_21)
smartctl_DEPENDENCIES = $(os_deps) $(am__append_9)
EXTRA_smartctl_SOURCES = os_darwin.cpp os_darwin.h os_linux.cpp \
	os_linux.h os_freebsd.cpp os_freebsd.h os_netbsd.cpp \
	os_netbsd.h os_openbsd.cpp os_openbsd.h os_os2.cpp os_os2.h \
	os_qnxnto.cpp os_qnxnto.h os_solaris.cpp os_solaris.h \
	os_win32.cpp os_generic.cpp os_generic.h aacraid.h cciss.cpp \
	cciss.h cissio_freebsd.h dev_areca.cpp dev_areca.h \
	dev_legacy.cpp linux_nvme_ioctl.h megaraid.h $(am__append_17)
smartd_SOURCES = smartd.cpp atacmdnames.cpp atacmdnames.h atacmds.cpp \
	atacmds.h dev_ata_cmd_set.cpp dev_ata_cmd_set.h \
	dev_intelliprop.cpp dev_interface.cpp dev_interface.h \
	dev_jmb39x_raid.cpp dev_tunnelled.h drivedb.h knowndrives.cpp \
	knowndrives.h nvmecmds.cpp nvmecmds.h scsicmds.cpp scsicmds.h \
	scsiata.cpp scsinvme.cpp static_assert.h utility.cpp utility.h \
	sg_unaligned.h $(am__append_10) $(am__append_14) \
	$(am__append_16) $(am__append_20)
smartd_LDADD = $(os_deps) $(os_libs) $(CAPNG_LDADD) $(SYSTEMD_LDADD) \
	$(am__append_11) $(am__append_22)
smartd_DEPENDENCIES = $(os_deps) $(am__append_12)
EXTRA_smartd_SOURCES = os_darwin.cpp os_darwin.h os_linux.cpp \
	os_linux.h os_freebsd.cpp os_freebsd.h os_netbsd.cpp \
	os_netbsd.h os_openbsd.cpp os_openbsd.h os_os2.cpp os_os2.h \
	os_qnxnto.cpp os_qnxnto.h os_solaris.cpp os_solaris.h \
	os_win32.cpp os_generic.cpp os_generic.h aacraid.h cciss.cpp \
	cciss.h cissio_freebsd.h dev_areca.cpp dev_areca.h \
	dev_legacy.cpp linux_nvme_ioctl.h freebsd_nvme_ioctl.h \
	netbsd_nvme_ioctl.h megaraid.h $(am__append_18)

# Exclude from source tarball
nodist_EXTRA_smartctl_SOURCES = os_solaris_ata.s
nodist_EXTRA_smartd_SOURCES = os_solaris_ata.s

# This block is required because Solaris uses manual page section 1m
# for administrative command (linux/freebsd use section 8) and Solaris
# uses manual page section 4 for file formats (linux/freebsd use
# section 5).  Automake can deal cleanly with man page sections 1-8
# and n, but NOT with sections of the form 1m.
#extra_MANS = smartd.conf.4 smartctl.1m smartd.1m \
#	$(am__append_23)
# For systems that adopts traditional manner
man_MANS = smartd.conf.5 smartctl.8 smartd.8 \
	$(am__append_24)
docsdir = $(docdir)
docs_DATA = \
        AUTHORS \
        ChangeLog \
        ChangeLog-6.0-7.0 \
        COPYING \
        INSTALL \
        NEWS \
        README \
        TODO \
        smartd.conf

examplesdir = $(exampledir)
examples_DATA = \
        examplescripts/README

examples_SCRIPTS = \
        examplescripts/Example1 \
        examplescripts/Example2 \
        examplescripts/Example3 \
        examplescripts/Example4 \
        examplescripts/Example5 \
        examplescripts/Example6 \
        examplescripts/Example7 \
        examplescripts/Example8

sysconf_DATA = smartd.conf
smartdscript_SCRIPTS = smartd_warning.sh
EXTRA_DIST = \
        .editorconfig \
        autogen.sh \
        ChangeLog-5.0-6.0 \
        cppcheck.sh \
        smartd.initd.in \
        smartd.cygwin.initd.in \
        smartd.freebsd.initd.in \
        smartd.8.in \
        smartctl.8.in \
        smartd.conf.5.in \
        smartd.conf \
        smartd.service.in \
        smartd_warning.sh.in \
        update-smart-drivedb.in \
        update-smart-drivedb.8.in \
        m4/pkg.m4 \
        os_darwin/com.smartmontools.smartd.plist.in \
        os_darwin/pkg/PackageInfo.in \
        os_darwin/pkg/Distribution.in \
        os_darwin/pkg/installer/README.html \
        os_darwin/pkg/root/usr/local/sbin/smart-pkg-uninstall \
        os_win32/default.manifest \
        os_win32/installer.nsi \
        os_win32/runcmd.c \
        os_win32/smartd_mailer.ps1 \
        os_win32/smartd_mailer.conf.sample.ps1 \
        os_win32/smartd_warning.cmd \
        os_win32/syslogevt.mc \
        os_win32/update-smart-drivedb.nsi \
        os_win32/versioninfo.rc.in \
        os_win32/wtssendmsg.c \
        $(docs_DATA) \
        $(examples_DATA) \
        $(examples_SCRIPTS)

CLEANFILES = smartd.8 smartd.1m smartd.8.html smartd.8.html.tmp \
	smartd.8.pdf smartd.8.txt smartctl.8 smartctl.1m \
	smartctl.8.html smartctl.8.html.tmp smartctl.8.pdf \
	smartctl.8.txt smartd.conf.5 smartd.conf.4 smartd.conf.5.html \
	smartd.conf.5.html.tmp smartd.conf.5.pdf smartd.conf.5.txt \
	smartd.initd smartd.cygwin.initd smartd.freebsd.initd \
	smartd.service smartd_warning.sh svnversion.h \
	update-smart-drivedb update-smart-drivedb.8 \
	update-smart-drivedb.1m update-smart-drivedb.8.html \
	update-smart-drivedb.8.html.tmp update-smart-drivedb.8.pdf \
	update-smart-drivedb.8.txt SMART $(am__append_27)

# 'make maintainer-clean' also removes files generated by './autogen.sh'
MAINTAINERCLEANFILES = \
        $(srcdir)/Makefile.in \
        $(srcdir)/aclocal.m4 \
        $(srcdir)/compile \
        $(srcdir)/configure \
        $(srcdir)/config.guess \
        $(srcdir)/config.h.in \
        $(srcdir)/config.h.in~ \
        $(srcdir)/config.sub \
        $(srcdir)/depcomp \
        $(srcdir)/install-sh \
        $(srcdir)/missing \
        $(srcdir)/m4/pkg.m4

drivedb_DATA = drivedb.h
#initd_DATA = $(initdfile)
##initd_DATA = com.smartmontools.smartd.plist
initd_DATA_install = install-initdDATA-null
#initd_DATA_install = install-initdDATA-generic
##initd_DATA_install = install-initdDATA-darwin
initd_DATA_uninstall = uninstall-initdDATA-null
#initd_DATA_uninstall = uninstall-initdDATA-generic
##initd_DATA_uninstall = uninstall-initdDATA-darwin
#initd_install_name = smartd$(smartd_suffix)
#systemdsystemunit_DATA = smartd.service

#
# Build man pages
#
MAN_FILTER = { \
    sed -e 's|CURRENT_SVN_VERSION|$(releaseversion)|g' \
        -e "s|CURRENT_SVN_DATE|`sed -n 's,^.*DATE[^"]*"\([^"]*\)".*$$,\1,p' svnversion.h`|g" \
        -e "s|CURRENT_SVN_REV|`sed -n 's,^.*REV[^"]*"\([^"]*\)".*$$,r\1,p' svnversion.h`|g" \
        -e 's|/usr/local/share/man/|$(mandir)/|g' \
        -e 's|/usr/local/sbin/|$(sbindir)/|g' \
        -e 's|/usr/local/share/doc/smartmontools/examplescripts/|!exampledir!|g' \
        -e 's|/usr/local/share/doc/smartmontools/|$(docsdir)/|g' \
        -e 's|!exampledir!|$(exampledir)/|g' \
        -e 's|/usr/local/etc/smartd\.conf|$(sysconfdir)/smartd.conf|g' \
        -e 's|/usr/local/etc/smart_drivedb\.h|$(sysconfdir)/smart_drivedb.h|g' \
        -e 's|/usr/local/etc/smartd_warning\.sh|$(smartdscriptdir)/smartd_warning.sh|g' \
        -e 's|\\fBmail\\fP|\\fB$(os_mailer)\\fP|g' \
        -e 's|\\'\''mail\\'\''|\\'\''$(os_mailer)\\'\''|g' \
        -e 's|/usr/bin/mail|/usr/bin/$(os_mailer)|g' \
        -e 's|RELEASE_6_0_DRIVEDB|$(DRIVEDB_BRANCH)|g' | \
    if test -n '$(drivedbdir)'; then \
      sed 's|/usr/local/share/smartmontools/drivedb\.h|$(drivedbdir)/drivedb.h|g' ; \
    else \
      sed '/^\.\\" %IF ENABLE_DRIVEDB/,/^\.\\" %ENDIF ENABLE_DRIVEDB/ s,^,.\\"\# ,' ; \
    fi | \
    if test '$(with_update_smart_drivedb)' = 'yes'; then \
      cat; \
    else \
      sed '/^\.\\" %IF ENABLE_UPDATE_SMART_DRIVEDB/,/^\.\\" %ENDIF ENABLE_UPDATE_SMART_DRIVEDB/ s,^,.\\"\# ,' ; \
    fi | \
    if test -n '$(initddir)'; then \
      sed 's|/usr/local/etc/rc\.d/init\.d/|$(initddir)/|g' ; \
    else \
      sed '/^\.\\" %IF ENABLE_INITSCRIPT/,/^\.\\" %ENDIF ENABLE_INITSCRIPT/ s,^,.\\"\# ,' ; \
    fi | \
    if test -n '$(savestates)'; then \
      sed 's|/usr/local/var/lib/smartmontools/smartd\.|$(savestates)|g' ; \
    else \
      sed '/^\.\\" %IF ENABLE_SAVESTATES/,/^\.\\" %ENDIF ENABLE_SAVESTATES/ s,^,.\\"\# ,' ; \
    fi | \
    if test -n '$(attributelog)'; then \
      sed 's|/usr/local/var/lib/smartmontools/attrlog\.|$(attributelog)|g' ; \
    else \
      sed '/^\.\\" %IF ENABLE_ATTRIBUTELOG/,/^\.\\" %ENDIF ENABLE_ATTRIBUTELOG/ s,^,.\\"\# ,' ; \
    fi | \
    if test -n '$(smartdplugindir)'; then \
      sed 's|/usr/local/etc/smartd_warning\.d|$(smartdplugindir)|g' ; \
    else \
      sed '/^\.\\" %IF ENABLE_SMARTDPLUGINDIR/,/^\.\\" %ENDIF ENABLE_SMARTDPLUGINDIR/ s,^,.\\"\# ,' ; \
    fi | \
    if test -n '$(CAPNG_LDADD)'; then \
      cat; \
    else \
      sed '/^\.\\" %IF ENABLE_CAPABILITIES/,/^\.\\" %ENDIF ENABLE_CAPABILITIES/ s,^,.\\"\# ,' ; \
    fi | \
    if test -n '$(SYSTEMD_LDADD)'; then \
      cat; \
    else \
      sed '/^\.\\" %IF ENABLE_SYSTEMD_NOTIFY/,/^\.\\" %ENDIF ENABLE_SYSTEMD_NOTIFY/ s,^,.\\"\# ,' ; \
    fi | \
    if test '$(with_nvme_devicescan)' = 'yes'; then \
      cat; \
    else \
      sed '/^\.\\" %IF ENABLE_NVME_DEVICESCAN/,/^\.\\" %ENDIF ENABLE_NVME_DEVICESCAN/ s,^,.\\"\# ,' ; \
    fi | \
    if test -n '$(os_man_filter)'; then \
      sed -e 's,OS_MAN_FILTER,$(os_man_filter),g' \
          -e '/^\.\\" %IF NOT OS .*$(os_man_filter)/,/^.\\" %ENDIF NOT OS .*$(os_man_filter)/ s,^,.\\"\# ,' \
          -e '/^\.\\" %IF OS .*$(os_man_filter)/,/^\.\\" %ENDIF OS .*$(os_man_filter)/ s,^,!!,' \
          -e '/^\.\\" %IF OS ./,/^\.\\" %ENDIF OS ./ s,^,.\\"\# ,' \
          -e '/^!*\.\\" %IF NOT OS ./,/^!*\.\\" %ENDIF NOT OS ./ s,^,!!,' \
          -e 's,^!!!*\.\\"! \(.*\)$$,\1 \\"\#,' \
          -e 's,^!!!*,,' ; \
    else \
      cat; \
    fi; }


# Build Solaris specific man pages
SOLARIS_MAN_FILTER = \
    sed -e '/^\.TH/s, \([58]\) , !!\1!! ,' \
        -e '/^\.BR/s, (\([578]\)), (!!\1!!),' \
        -e 's,\\fP(\([578]\)),\\fP(!!\1!!),g' \
        -e 's,!!5!!,4,g' -e 's,!!7!!,5,g' -e 's,!!8!!,1m,g' \
        -e 's,/var/log/messages,/var/adm/messages,g'


# Convert man pages into .html, .pdf and .txt
# TODO: configure
MAN2HTML = man2html
#MAN2HTML = groff -man -Thtml
MAN2PDF = man -Tpdf -l
#MAN2PDF = groff -man -Tpdf
MAN2TXT = groff -man -Tascii -P'-bcou'

# Remove HTTP header and fix links in man2html output
FIXHTML = sed -e '1s,^Content-type.*,,' \
              -e 's,<A HREF="[^"]*/man2html?\([1-8]\)+\(smart[cd][.a-z]*\)">,<A HREF="\2.\1.html">,g' \
              -e 's,<A HREF="[^"]*/man2html">,<A HREF=".">,g' \
              -e 's,<A HREF="[^"]*/man2html?[^"]*">\([^<]*\)</A>,\1,g' \
              -e 's,<A HREF="mailto:[^s][^m][^a][^"]*">\([^<]*\)</A>,\1,g'

CPPCHECKFLAGS = 

# Convert version for VERSIONINFO resource: 6.6 r4519 -> 6.6.0.4519,
# set description, name, version and year
WIN_RC_FILTER = { \
    ver=`echo '$(PACKAGE_VERSION).0' | sed -n 's,^\([0-9]*\.[0-9]*\.[0-9]*\).*$$,\1,p'` && \
    rev=`sed -n 's,^.*REV[^"]*"\([0-9]*\).*$$,\1,p' svnversion.h` && \
    txtver="$${ver:-0.0.0}.$${rev:-0}" && binver=`echo "$$txtver" | sed 's|\.|,|g'` && \
    yy=`sed -n 's,^.*DATE[^"]*"20\([0-9][0-9]\).*$$,\1,p' svnversion.h` && yy="$${yy:-XX}" && \
    sed -e "s|@DESC@|$$d|" -e "s|@NAME@|$$n|" -e "s|@BINARY_VERSION@|$$binver|g" \
        -e "s|@TEXT_VERSION@|$$txtver|g" -e "s|@YY@|$$yy|g"; }

WIN_MAKE_RES = \
    echo "n=$$n d=\"$$d"'"; $$(WIN_RC_FILTER) < $< > $@'; \
    $(WIN_RC_FILTER) < $< > $@

WIN_APP_MANIFEST = \
    if test -n '$(os_win32_manifest)'; then \
      echo "echo '1 24 \"$(srcdir)/$(os_win32_manifest)\"' >> $@"; \
      echo '1 24 "$(srcdir)/$(os_win32_manifest)"' >> $@; \
    fi

#win_bits = 32

# Definitions for Windows distribution
win_bits = 64
distdir_win32 = $(PACKAGE)-$(VERSION).win$(win_bits)
distzip_win32 = $(PACKAGE)-$(VERSION).win$(win_bits).zip
distinst_win32 = $(PACKAGE)-$(VERSION).win$(win_bits)-setup.exe
exedir_win32 = $(distdir_win32)/bin
docdir_win32 = $(distdir_win32)/doc
EXEFILES_WIN32 = $(exedir_win32)/smartctl.exe \
	$(exedir_win32)/smartctl-nc.exe \
	$(exedir_win32)/smartd.exe \
	$(exedir_win32)/smartd_mailer.ps1 \
	$(exedir_win32)/smartd_mailer.conf.sample.ps1 \
	$(exedir_win32)/smartd_warning.cmd \
	$(exedir_win32)/runcmda.exe \
	$(exedir_win32)/runcmdu.exe \
	$(exedir_win32)/wtssendmsg.exe \
	$(am__append_25)
FILES_WIN32 = $(EXEFILES_WIN32) \
	$(docdir_win32)/AUTHORS.txt \
	$(docdir_win32)/ChangeLog.txt \
	$(docdir_win32)/ChangeLog-6.0-7.0.txt \
	$(docdir_win32)/COPYING.txt \
	$(docdir_win32)/INSTALL.txt \
	$(docdir_win32)/NEWS.txt \
	$(docdir_win32)/README.txt \
	$(docdir_win32)/TODO.txt \
	$(docdir_win32)/checksums$(win_bits).txt \
	$(docdir_win32)/smartd.conf \
	$(docdir_win32)/smartctl.8.html \
	$(docdir_win32)/smartctl.8.pdf \
	$(docdir_win32)/smartd.8.html \
	$(docdir_win32)/smartd.8.pdf \
	$(docdir_win32)/smartd.conf.5.html \
	$(docdir_win32)/smartd.conf.5.pdf \
	$(am__append_26)

# Note: Only use without options to be compatible with all variants
UNIX2DOS = unix2dos

# Build os_win32/vc14/{config.h,smart*.rc,svnversion.h} for MSVC14 from MinGW files
vcver = 14
CONFIG_VC_FILES = \
        $(srcdir)/os_win32/vc$(vcver)/config.h \
        $(srcdir)/os_win32/vc$(vcver)/smartctl_res.rc \
        $(srcdir)/os_win32/vc$(vcver)/smartd_res.rc \
        $(srcdir)/os_win32/vc$(vcver)/svnversion.h


# Definitions for OSX distribution
#distdir_darwin = $(PACKAGE)-$(VERSION).darwin
#dmg_darwin = $(PACKAGE)-$(VERSION).dmg
#pkg_darwin = $(PACKAGE)-$(VERSION).pkg
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .cpp .c .s .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in: # $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure: # $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4): # $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@test -f $@ || rm -f stamp-h1
	@test -f $@ || $(MAKE) $(AM_MAKEFLAGS) stamp-h1

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in: # $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-sbinPROGRAMS: $(sbin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(sbin_PROGRAMS)'; test -n "$(sbindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(sbindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(sbindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(sbindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(sbindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-sbinPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(sbin_PROGRAMS)'; test -n "$(sbindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(sbindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(sbindir)" && rm -f $$files

clean-sbinPROGRAMS:
	-test -z "$(sbin_PROGRAMS)" || rm -f $(sbin_PROGRAMS)

smartctl$(EXEEXT): $(smartctl_OBJECTS) $(smartctl_DEPENDENCIES) $(EXTRA_smartctl_DEPENDENCIES) 
	@rm -f smartctl$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(smartctl_OBJECTS) $(smartctl_LDADD) $(LIBS)

smartd$(EXEEXT): $(smartd_OBJECTS) $(smartd_DEPENDENCIES) $(EXTRA_smartd_DEPENDENCIES) 
	@rm -f smartd$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(smartd_OBJECTS) $(smartd_LDADD) $(LIBS)
install-examplesSCRIPTS: $(examples_SCRIPTS)
	@$(NORMAL_INSTALL)
	@list='$(examples_SCRIPTS)'; test -n "$(examplesdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(examplesdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(examplesdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(examplesdir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(examplesdir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-examplesSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(examples_SCRIPTS)'; test -n "$(examplesdir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	dir='$(DESTDIR)$(examplesdir)'; $(am__uninstall_files_from_dir)
install-sbinSCRIPTS: $(sbin_SCRIPTS)
	@$(NORMAL_INSTALL)
	@list='$(sbin_SCRIPTS)'; test -n "$(sbindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(sbindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(sbindir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(sbindir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(sbindir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-sbinSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(sbin_SCRIPTS)'; test -n "$(sbindir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	dir='$(DESTDIR)$(sbindir)'; $(am__uninstall_files_from_dir)
install-smartdscriptSCRIPTS: $(smartdscript_SCRIPTS)
	@$(NORMAL_INSTALL)
	@list='$(smartdscript_SCRIPTS)'; test -n "$(smartdscriptdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(smartdscriptdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(smartdscriptdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  if test -f "$$d$$p"; then echo "$$d$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n' \
	    -e 'h;s|.*|.|' \
	    -e 'p;x;s,.*/,,;$(transform)' | sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1; } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) { files[d] = files[d] " " $$1; \
	      if (++n[d] == $(am__install_max)) { \
		print "f", d, files[d]; n[d] = 0; files[d] = "" } } \
	    else { print "f", d "/" $$4, $$1 } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	     if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	     test -z "$$files" || { \
	       echo " $(INSTALL_SCRIPT) $$files '$(DESTDIR)$(smartdscriptdir)$$dir'"; \
	       $(INSTALL_SCRIPT) $$files "$(DESTDIR)$(smartdscriptdir)$$dir" || exit $$?; \
	     } \
	; done

uninstall-smartdscriptSCRIPTS:
	@$(NORMAL_UNINSTALL)
	@list='$(smartdscript_SCRIPTS)'; test -n "$(smartdscriptdir)" || exit 0; \
	files=`for p in $$list; do echo "$$p"; done | \
	       sed -e 's,.*/,,;$(transform)'`; \
	dir='$(DESTDIR)$(smartdscriptdir)'; $(am__uninstall_files_from_dir)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/atacmdnames.Po # am--include-marker
include ./$(DEPDIR)/atacmds.Po # am--include-marker
include ./$(DEPDIR)/ataidentify.Po # am--include-marker
include ./$(DEPDIR)/ataprint.Po # am--include-marker
include ./$(DEPDIR)/cciss.Po # am--include-marker
include ./$(DEPDIR)/daemon_win32.Po # am--include-marker
include ./$(DEPDIR)/dev_areca.Po # am--include-marker
include ./$(DEPDIR)/dev_ata_cmd_set.Po # am--include-marker
include ./$(DEPDIR)/dev_intelliprop.Po # am--include-marker
include ./$(DEPDIR)/dev_interface.Po # am--include-marker
include ./$(DEPDIR)/dev_jmb39x_raid.Po # am--include-marker
include ./$(DEPDIR)/dev_legacy.Po # am--include-marker
include ./$(DEPDIR)/getopt.Po # am--include-marker
include ./$(DEPDIR)/getopt1.Po # am--include-marker
include ./$(DEPDIR)/json.Po # am--include-marker
include ./$(DEPDIR)/knowndrives.Po # am--include-marker
include ./$(DEPDIR)/nvmecmds.Po # am--include-marker
include ./$(DEPDIR)/nvmeprint.Po # am--include-marker
include ./$(DEPDIR)/os_darwin.Po # am--include-marker
include ./$(DEPDIR)/os_freebsd.Po # am--include-marker
include ./$(DEPDIR)/os_generic.Po # am--include-marker
include ./$(DEPDIR)/os_linux.Po # am--include-marker
include ./$(DEPDIR)/os_netbsd.Po # am--include-marker
include ./$(DEPDIR)/os_openbsd.Po # am--include-marker
include ./$(DEPDIR)/os_os2.Po # am--include-marker
include ./$(DEPDIR)/os_qnxnto.Po # am--include-marker
include ./$(DEPDIR)/os_solaris.Po # am--include-marker
include ./$(DEPDIR)/os_win32.Po # am--include-marker
include ./$(DEPDIR)/popen_win32.Po # am--include-marker
include ./$(DEPDIR)/regcomp.Po # am--include-marker
include ./$(DEPDIR)/regex.Po # am--include-marker
include ./$(DEPDIR)/regex_internal.Po # am--include-marker
include ./$(DEPDIR)/regexec.Po # am--include-marker
include ./$(DEPDIR)/scsiata.Po # am--include-marker
include ./$(DEPDIR)/scsicmds.Po # am--include-marker
include ./$(DEPDIR)/scsinvme.Po # am--include-marker
include ./$(DEPDIR)/scsiprint.Po # am--include-marker
include ./$(DEPDIR)/smartctl.Po # am--include-marker
include ./$(DEPDIR)/smartd.Po # am--include-marker
include ./$(DEPDIR)/syslog_win32.Po # am--include-marker
include ./$(DEPDIR)/utility.Po # am--include-marker
include ./$(DEPDIR)/wmiquery.Po # am--include-marker

$(am__depfiles_remade):
	@$(MKDIR_P) $(@D)
	@echo '# dummy' >$@-t && $(am__mv) $@-t $@

am--depfiles: $(am__depfiles_remade)

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

getopt.o: getopt/getopt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT getopt.o -MD -MP -MF $(DEPDIR)/getopt.Tpo -c -o getopt.o `test -f 'getopt/getopt.c' || echo '$(srcdir)/'`getopt/getopt.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/getopt.Tpo $(DEPDIR)/getopt.Po
#	$(AM_V_CC)source='getopt/getopt.c' object='getopt.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o getopt.o `test -f 'getopt/getopt.c' || echo '$(srcdir)/'`getopt/getopt.c

getopt.obj: getopt/getopt.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT getopt.obj -MD -MP -MF $(DEPDIR)/getopt.Tpo -c -o getopt.obj `if test -f 'getopt/getopt.c'; then $(CYGPATH_W) 'getopt/getopt.c'; else $(CYGPATH_W) '$(srcdir)/getopt/getopt.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/getopt.Tpo $(DEPDIR)/getopt.Po
#	$(AM_V_CC)source='getopt/getopt.c' object='getopt.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o getopt.obj `if test -f 'getopt/getopt.c'; then $(CYGPATH_W) 'getopt/getopt.c'; else $(CYGPATH_W) '$(srcdir)/getopt/getopt.c'; fi`

getopt1.o: getopt/getopt1.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT getopt1.o -MD -MP -MF $(DEPDIR)/getopt1.Tpo -c -o getopt1.o `test -f 'getopt/getopt1.c' || echo '$(srcdir)/'`getopt/getopt1.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/getopt1.Tpo $(DEPDIR)/getopt1.Po
#	$(AM_V_CC)source='getopt/getopt1.c' object='getopt1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o getopt1.o `test -f 'getopt/getopt1.c' || echo '$(srcdir)/'`getopt/getopt1.c

getopt1.obj: getopt/getopt1.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT getopt1.obj -MD -MP -MF $(DEPDIR)/getopt1.Tpo -c -o getopt1.obj `if test -f 'getopt/getopt1.c'; then $(CYGPATH_W) 'getopt/getopt1.c'; else $(CYGPATH_W) '$(srcdir)/getopt/getopt1.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/getopt1.Tpo $(DEPDIR)/getopt1.Po
#	$(AM_V_CC)source='getopt/getopt1.c' object='getopt1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o getopt1.obj `if test -f 'getopt/getopt1.c'; then $(CYGPATH_W) 'getopt/getopt1.c'; else $(CYGPATH_W) '$(srcdir)/getopt/getopt1.c'; fi`

regex.o: regex/regex.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regex.o -MD -MP -MF $(DEPDIR)/regex.Tpo -c -o regex.o `test -f 'regex/regex.c' || echo '$(srcdir)/'`regex/regex.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/regex.Tpo $(DEPDIR)/regex.Po
#	$(AM_V_CC)source='regex/regex.c' object='regex.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regex.o `test -f 'regex/regex.c' || echo '$(srcdir)/'`regex/regex.c

regex.obj: regex/regex.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regex.obj -MD -MP -MF $(DEPDIR)/regex.Tpo -c -o regex.obj `if test -f 'regex/regex.c'; then $(CYGPATH_W) 'regex/regex.c'; else $(CYGPATH_W) '$(srcdir)/regex/regex.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/regex.Tpo $(DEPDIR)/regex.Po
#	$(AM_V_CC)source='regex/regex.c' object='regex.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regex.obj `if test -f 'regex/regex.c'; then $(CYGPATH_W) 'regex/regex.c'; else $(CYGPATH_W) '$(srcdir)/regex/regex.c'; fi`

regcomp.o: regex/regcomp.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regcomp.o -MD -MP -MF $(DEPDIR)/regcomp.Tpo -c -o regcomp.o `test -f 'regex/regcomp.c' || echo '$(srcdir)/'`regex/regcomp.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/regcomp.Tpo $(DEPDIR)/regcomp.Po
#	$(AM_V_CC)source='regex/regcomp.c' object='regcomp.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regcomp.o `test -f 'regex/regcomp.c' || echo '$(srcdir)/'`regex/regcomp.c

regcomp.obj: regex/regcomp.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regcomp.obj -MD -MP -MF $(DEPDIR)/regcomp.Tpo -c -o regcomp.obj `if test -f 'regex/regcomp.c'; then $(CYGPATH_W) 'regex/regcomp.c'; else $(CYGPATH_W) '$(srcdir)/regex/regcomp.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/regcomp.Tpo $(DEPDIR)/regcomp.Po
#	$(AM_V_CC)source='regex/regcomp.c' object='regcomp.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regcomp.obj `if test -f 'regex/regcomp.c'; then $(CYGPATH_W) 'regex/regcomp.c'; else $(CYGPATH_W) '$(srcdir)/regex/regcomp.c'; fi`

regexec.o: regex/regexec.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regexec.o -MD -MP -MF $(DEPDIR)/regexec.Tpo -c -o regexec.o `test -f 'regex/regexec.c' || echo '$(srcdir)/'`regex/regexec.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/regexec.Tpo $(DEPDIR)/regexec.Po
#	$(AM_V_CC)source='regex/regexec.c' object='regexec.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regexec.o `test -f 'regex/regexec.c' || echo '$(srcdir)/'`regex/regexec.c

regexec.obj: regex/regexec.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regexec.obj -MD -MP -MF $(DEPDIR)/regexec.Tpo -c -o regexec.obj `if test -f 'regex/regexec.c'; then $(CYGPATH_W) 'regex/regexec.c'; else $(CYGPATH_W) '$(srcdir)/regex/regexec.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/regexec.Tpo $(DEPDIR)/regexec.Po
#	$(AM_V_CC)source='regex/regexec.c' object='regexec.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regexec.obj `if test -f 'regex/regexec.c'; then $(CYGPATH_W) 'regex/regexec.c'; else $(CYGPATH_W) '$(srcdir)/regex/regexec.c'; fi`

regex_internal.o: regex/regex_internal.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regex_internal.o -MD -MP -MF $(DEPDIR)/regex_internal.Tpo -c -o regex_internal.o `test -f 'regex/regex_internal.c' || echo '$(srcdir)/'`regex/regex_internal.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/regex_internal.Tpo $(DEPDIR)/regex_internal.Po
#	$(AM_V_CC)source='regex/regex_internal.c' object='regex_internal.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regex_internal.o `test -f 'regex/regex_internal.c' || echo '$(srcdir)/'`regex/regex_internal.c

regex_internal.obj: regex/regex_internal.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -MT regex_internal.obj -MD -MP -MF $(DEPDIR)/regex_internal.Tpo -c -o regex_internal.obj `if test -f 'regex/regex_internal.c'; then $(CYGPATH_W) 'regex/regex_internal.c'; else $(CYGPATH_W) '$(srcdir)/regex/regex_internal.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/regex_internal.Tpo $(DEPDIR)/regex_internal.Po
#	$(AM_V_CC)source='regex/regex_internal.c' object='regex_internal.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS) -c -o regex_internal.obj `if test -f 'regex/regex_internal.c'; then $(CYGPATH_W) 'regex/regex_internal.c'; else $(CYGPATH_W) '$(srcdir)/regex/regex_internal.c'; fi`

.cpp.o:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

popen_win32.o: os_win32/popen_win32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT popen_win32.o -MD -MP -MF $(DEPDIR)/popen_win32.Tpo -c -o popen_win32.o `test -f 'os_win32/popen_win32.cpp' || echo '$(srcdir)/'`os_win32/popen_win32.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/popen_win32.Tpo $(DEPDIR)/popen_win32.Po
#	$(AM_V_CXX)source='os_win32/popen_win32.cpp' object='popen_win32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o popen_win32.o `test -f 'os_win32/popen_win32.cpp' || echo '$(srcdir)/'`os_win32/popen_win32.cpp

popen_win32.obj: os_win32/popen_win32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT popen_win32.obj -MD -MP -MF $(DEPDIR)/popen_win32.Tpo -c -o popen_win32.obj `if test -f 'os_win32/popen_win32.cpp'; then $(CYGPATH_W) 'os_win32/popen_win32.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/popen_win32.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/popen_win32.Tpo $(DEPDIR)/popen_win32.Po
#	$(AM_V_CXX)source='os_win32/popen_win32.cpp' object='popen_win32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o popen_win32.obj `if test -f 'os_win32/popen_win32.cpp'; then $(CYGPATH_W) 'os_win32/popen_win32.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/popen_win32.cpp'; fi`

wmiquery.o: os_win32/wmiquery.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT wmiquery.o -MD -MP -MF $(DEPDIR)/wmiquery.Tpo -c -o wmiquery.o `test -f 'os_win32/wmiquery.cpp' || echo '$(srcdir)/'`os_win32/wmiquery.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/wmiquery.Tpo $(DEPDIR)/wmiquery.Po
#	$(AM_V_CXX)source='os_win32/wmiquery.cpp' object='wmiquery.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o wmiquery.o `test -f 'os_win32/wmiquery.cpp' || echo '$(srcdir)/'`os_win32/wmiquery.cpp

wmiquery.obj: os_win32/wmiquery.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT wmiquery.obj -MD -MP -MF $(DEPDIR)/wmiquery.Tpo -c -o wmiquery.obj `if test -f 'os_win32/wmiquery.cpp'; then $(CYGPATH_W) 'os_win32/wmiquery.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/wmiquery.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/wmiquery.Tpo $(DEPDIR)/wmiquery.Po
#	$(AM_V_CXX)source='os_win32/wmiquery.cpp' object='wmiquery.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o wmiquery.obj `if test -f 'os_win32/wmiquery.cpp'; then $(CYGPATH_W) 'os_win32/wmiquery.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/wmiquery.cpp'; fi`

daemon_win32.o: os_win32/daemon_win32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT daemon_win32.o -MD -MP -MF $(DEPDIR)/daemon_win32.Tpo -c -o daemon_win32.o `test -f 'os_win32/daemon_win32.cpp' || echo '$(srcdir)/'`os_win32/daemon_win32.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/daemon_win32.Tpo $(DEPDIR)/daemon_win32.Po
#	$(AM_V_CXX)source='os_win32/daemon_win32.cpp' object='daemon_win32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o daemon_win32.o `test -f 'os_win32/daemon_win32.cpp' || echo '$(srcdir)/'`os_win32/daemon_win32.cpp

daemon_win32.obj: os_win32/daemon_win32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT daemon_win32.obj -MD -MP -MF $(DEPDIR)/daemon_win32.Tpo -c -o daemon_win32.obj `if test -f 'os_win32/daemon_win32.cpp'; then $(CYGPATH_W) 'os_win32/daemon_win32.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/daemon_win32.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/daemon_win32.Tpo $(DEPDIR)/daemon_win32.Po
#	$(AM_V_CXX)source='os_win32/daemon_win32.cpp' object='daemon_win32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o daemon_win32.obj `if test -f 'os_win32/daemon_win32.cpp'; then $(CYGPATH_W) 'os_win32/daemon_win32.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/daemon_win32.cpp'; fi`

syslog_win32.o: os_win32/syslog_win32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT syslog_win32.o -MD -MP -MF $(DEPDIR)/syslog_win32.Tpo -c -o syslog_win32.o `test -f 'os_win32/syslog_win32.cpp' || echo '$(srcdir)/'`os_win32/syslog_win32.cpp
	$(AM_V_at)$(am__mv) $(DEPDIR)/syslog_win32.Tpo $(DEPDIR)/syslog_win32.Po
#	$(AM_V_CXX)source='os_win32/syslog_win32.cpp' object='syslog_win32.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o syslog_win32.o `test -f 'os_win32/syslog_win32.cpp' || echo '$(srcdir)/'`os_win32/syslog_win32.cpp

syslog_win32.obj: os_win32/syslog_win32.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT syslog_win32.obj -MD -MP -MF $(DEPDIR)/syslog_win32.Tpo -c -o syslog_win32.obj `if test -f 'os_win32/syslog_win32.cpp'; then $(CYGPATH_W) 'os_win32/syslog_win32.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/syslog_win32.cpp'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/syslog_win32.Tpo $(DEPDIR)/syslog_win32.Po
#	$(AM_V_CXX)source='os_win32/syslog_win32.cpp' object='syslog_win32.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o syslog_win32.obj `if test -f 'os_win32/syslog_win32.cpp'; then $(CYGPATH_W) 'os_win32/syslog_win32.cpp'; else $(CYGPATH_W) '$(srcdir)/os_win32/syslog_win32.cpp'; fi`

.s.o:
	$(AM_V_CCAS)$(CCASCOMPILE) -c -o $@ $<

.s.obj:
	$(AM_V_CCAS)$(CCASCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`
install-man5: $(man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(man_MANS)'; \
	test -n "$(man5dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man5dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man5dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.5[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^5][0-9a-z]*$$,5,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man5dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man5dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man5dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man5dir)" || exit $$?; }; \
	done; }

uninstall-man5:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man5dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.5[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^5][0-9a-z]*$$,5,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man5dir)'; $(am__uninstall_files_from_dir)
install-man8: $(man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(man_MANS)'; \
	test -n "$(man8dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man8dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man8dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.8[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^8][0-9a-z]*$$,8,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man8dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man8dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man8dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man8dir)" || exit $$?; }; \
	done; }

uninstall-man8:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man8dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.8[a-z]*$$/p'; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^8][0-9a-z]*$$,8,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man8dir)'; $(am__uninstall_files_from_dir)
install-docsDATA: $(docs_DATA)
	@$(NORMAL_INSTALL)
	@list='$(docs_DATA)'; test -n "$(docsdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(docsdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(docsdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(docsdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(docsdir)" || exit $$?; \
	done

uninstall-docsDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(docs_DATA)'; test -n "$(docsdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(docsdir)'; $(am__uninstall_files_from_dir)
install-drivedbDATA: $(drivedb_DATA)
	@$(NORMAL_INSTALL)
	@list='$(drivedb_DATA)'; test -n "$(drivedbdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(drivedbdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(drivedbdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(drivedbdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(drivedbdir)" || exit $$?; \
	done

uninstall-drivedbDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(drivedb_DATA)'; test -n "$(drivedbdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(drivedbdir)'; $(am__uninstall_files_from_dir)
install-examplesDATA: $(examples_DATA)
	@$(NORMAL_INSTALL)
	@list='$(examples_DATA)'; test -n "$(examplesdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(examplesdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(examplesdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(examplesdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(examplesdir)" || exit $$?; \
	done

uninstall-examplesDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(examples_DATA)'; test -n "$(examplesdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(examplesdir)'; $(am__uninstall_files_from_dir)
install-systemdsystemunitDATA: $(systemdsystemunit_DATA)
	@$(NORMAL_INSTALL)
	@list='$(systemdsystemunit_DATA)'; test -n "$(systemdsystemunitdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(systemdsystemunitdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(systemdsystemunitdir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(systemdsystemunitdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(systemdsystemunitdir)" || exit $$?; \
	done

uninstall-systemdsystemunitDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(systemdsystemunit_DATA)'; test -n "$(systemdsystemunitdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(systemdsystemunitdir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	@echo WARNING: "Support for distribution archives compressed with" \
		       "legacy program 'compress' is deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	@echo WARNING: "Support for shar distribution archives is" \
	               "deprecated." >&2
	@echo WARNING: "It will be removed altogether in Automake 2.0" >&2
	shar $(distdir) | eval GZIP= gzip $(GZIP_ENV) -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  eval GZIP= gzip $(GZIP_ENV) -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_build/sub $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build/sub \
	  && ../../configure \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	    --srcdir=../.. --prefix="$$dc_install_base" \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-local:
all-am: Makefile $(PROGRAMS) $(SCRIPTS) $(MANS) $(DATA) config.h \
		all-local
installdirs: installdirs-local
	for dir in "$(DESTDIR)$(sbindir)" "$(DESTDIR)$(examplesdir)" "$(DESTDIR)$(sbindir)" "$(DESTDIR)$(smartdscriptdir)" "$(DESTDIR)$(man5dir)" "$(DESTDIR)$(man8dir)" "$(DESTDIR)$(docsdir)" "$(DESTDIR)$(drivedbdir)" "$(DESTDIR)$(examplesdir)" "$(DESTDIR)$(initddir)" "$(DESTDIR)$(sysconfdir)" "$(DESTDIR)$(systemdsystemunitdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-am

clean-am: clean-generic clean-sbinPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
		-rm -f ./$(DEPDIR)/atacmdnames.Po
	-rm -f ./$(DEPDIR)/atacmds.Po
	-rm -f ./$(DEPDIR)/ataidentify.Po
	-rm -f ./$(DEPDIR)/ataprint.Po
	-rm -f ./$(DEPDIR)/cciss.Po
	-rm -f ./$(DEPDIR)/daemon_win32.Po
	-rm -f ./$(DEPDIR)/dev_areca.Po
	-rm -f ./$(DEPDIR)/dev_ata_cmd_set.Po
	-rm -f ./$(DEPDIR)/dev_intelliprop.Po
	-rm -f ./$(DEPDIR)/dev_interface.Po
	-rm -f ./$(DEPDIR)/dev_jmb39x_raid.Po
	-rm -f ./$(DEPDIR)/dev_legacy.Po
	-rm -f ./$(DEPDIR)/getopt.Po
	-rm -f ./$(DEPDIR)/getopt1.Po
	-rm -f ./$(DEPDIR)/json.Po
	-rm -f ./$(DEPDIR)/knowndrives.Po
	-rm -f ./$(DEPDIR)/nvmecmds.Po
	-rm -f ./$(DEPDIR)/nvmeprint.Po
	-rm -f ./$(DEPDIR)/os_darwin.Po
	-rm -f ./$(DEPDIR)/os_freebsd.Po
	-rm -f ./$(DEPDIR)/os_generic.Po
	-rm -f ./$(DEPDIR)/os_linux.Po
	-rm -f ./$(DEPDIR)/os_netbsd.Po
	-rm -f ./$(DEPDIR)/os_openbsd.Po
	-rm -f ./$(DEPDIR)/os_os2.Po
	-rm -f ./$(DEPDIR)/os_qnxnto.Po
	-rm -f ./$(DEPDIR)/os_solaris.Po
	-rm -f ./$(DEPDIR)/os_win32.Po
	-rm -f ./$(DEPDIR)/popen_win32.Po
	-rm -f ./$(DEPDIR)/regcomp.Po
	-rm -f ./$(DEPDIR)/regex.Po
	-rm -f ./$(DEPDIR)/regex_internal.Po
	-rm -f ./$(DEPDIR)/regexec.Po
	-rm -f ./$(DEPDIR)/scsiata.Po
	-rm -f ./$(DEPDIR)/scsicmds.Po
	-rm -f ./$(DEPDIR)/scsinvme.Po
	-rm -f ./$(DEPDIR)/scsiprint.Po
	-rm -f ./$(DEPDIR)/smartctl.Po
	-rm -f ./$(DEPDIR)/smartd.Po
	-rm -f ./$(DEPDIR)/syslog_win32.Po
	-rm -f ./$(DEPDIR)/utility.Po
	-rm -f ./$(DEPDIR)/wmiquery.Po
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-data-local install-docsDATA \
	install-drivedbDATA install-examplesDATA \
	install-examplesSCRIPTS install-initdDATA install-man \
	install-smartdscriptSCRIPTS install-systemdsystemunitDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-sbinPROGRAMS install-sbinSCRIPTS \
	install-sysconfDATA

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man5 install-man8

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
		-rm -f ./$(DEPDIR)/atacmdnames.Po
	-rm -f ./$(DEPDIR)/atacmds.Po
	-rm -f ./$(DEPDIR)/ataidentify.Po
	-rm -f ./$(DEPDIR)/ataprint.Po
	-rm -f ./$(DEPDIR)/cciss.Po
	-rm -f ./$(DEPDIR)/daemon_win32.Po
	-rm -f ./$(DEPDIR)/dev_areca.Po
	-rm -f ./$(DEPDIR)/dev_ata_cmd_set.Po
	-rm -f ./$(DEPDIR)/dev_intelliprop.Po
	-rm -f ./$(DEPDIR)/dev_interface.Po
	-rm -f ./$(DEPDIR)/dev_jmb39x_raid.Po
	-rm -f ./$(DEPDIR)/dev_legacy.Po
	-rm -f ./$(DEPDIR)/getopt.Po
	-rm -f ./$(DEPDIR)/getopt1.Po
	-rm -f ./$(DEPDIR)/json.Po
	-rm -f ./$(DEPDIR)/knowndrives.Po
	-rm -f ./$(DEPDIR)/nvmecmds.Po
	-rm -f ./$(DEPDIR)/nvmeprint.Po
	-rm -f ./$(DEPDIR)/os_darwin.Po
	-rm -f ./$(DEPDIR)/os_freebsd.Po
	-rm -f ./$(DEPDIR)/os_generic.Po
	-rm -f ./$(DEPDIR)/os_linux.Po
	-rm -f ./$(DEPDIR)/os_netbsd.Po
	-rm -f ./$(DEPDIR)/os_openbsd.Po
	-rm -f ./$(DEPDIR)/os_os2.Po
	-rm -f ./$(DEPDIR)/os_qnxnto.Po
	-rm -f ./$(DEPDIR)/os_solaris.Po
	-rm -f ./$(DEPDIR)/os_win32.Po
	-rm -f ./$(DEPDIR)/popen_win32.Po
	-rm -f ./$(DEPDIR)/regcomp.Po
	-rm -f ./$(DEPDIR)/regex.Po
	-rm -f ./$(DEPDIR)/regex_internal.Po
	-rm -f ./$(DEPDIR)/regexec.Po
	-rm -f ./$(DEPDIR)/scsiata.Po
	-rm -f ./$(DEPDIR)/scsicmds.Po
	-rm -f ./$(DEPDIR)/scsinvme.Po
	-rm -f ./$(DEPDIR)/scsiprint.Po
	-rm -f ./$(DEPDIR)/smartctl.Po
	-rm -f ./$(DEPDIR)/smartd.Po
	-rm -f ./$(DEPDIR)/syslog_win32.Po
	-rm -f ./$(DEPDIR)/utility.Po
	-rm -f ./$(DEPDIR)/wmiquery.Po
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-docsDATA uninstall-drivedbDATA \
	uninstall-examplesDATA uninstall-examplesSCRIPTS \
	uninstall-initdDATA uninstall-man uninstall-sbinPROGRAMS \
	uninstall-sbinSCRIPTS uninstall-smartdscriptSCRIPTS \
	uninstall-sysconfDATA uninstall-systemdsystemunitDATA

uninstall-man: uninstall-man5 uninstall-man8

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am all-local am--depfiles am--refresh \
	check check-am clean clean-cscope clean-generic \
	clean-sbinPROGRAMS cscope cscopelist-am ctags ctags-am dist \
	dist-all dist-bzip2 dist-gzip dist-lzip dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-data install-data-am \
	install-data-local install-docsDATA install-drivedbDATA \
	install-dvi install-dvi-am install-examplesDATA \
	install-examplesSCRIPTS install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-initdDATA install-man install-man5 install-man8 \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-sbinPROGRAMS install-sbinSCRIPTS \
	install-smartdscriptSCRIPTS install-strip install-sysconfDATA \
	install-systemdsystemunitDATA installcheck installcheck-am \
	installdirs installdirs-local maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-docsDATA uninstall-drivedbDATA \
	uninstall-examplesDATA uninstall-examplesSCRIPTS \
	uninstall-initdDATA uninstall-man uninstall-man5 \
	uninstall-man8 uninstall-sbinPROGRAMS uninstall-sbinSCRIPTS \
	uninstall-smartdscriptSCRIPTS uninstall-sysconfDATA \
	uninstall-systemdsystemunitDATA

.PRECIOUS: Makefile




#all-local: $(extra_MANS)
#install-man: $(extra_MANS)
#	@$(NORMAL_INSTALL)
#	$(MKDIR_P) '$(DESTDIR)$(mandir)/man4'
#	$(MKDIR_P) '$(DESTDIR)$(mandir)/man1m'
#	for i in $(extra_MANS); do \
#	  if test -f $(srcdir)/$$i; then file=$(srcdir)/$$i; \
#	  else file=$$i; fi; \
#	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
#	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
#	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
#	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
#	  echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(mandir)/man$$ext/$$inst'"; \
#	  $(INSTALL_DATA) "$$file" "$(DESTDIR)$(mandir)/man$$ext/$$inst"; \
#	done
#uninstall-man:
#	@$(NORMAL_UNINSTALL)
#	for i in $(extra_MANS); do \
#	  if test -f $(srcdir)/$$i; then file=$(srcdir)/$$i; \
#	  else file=$$i; fi; \
#	  ext=`echo $$i | sed -e 's/^.*\\.//'`; \
#	  inst=`echo $$i | sed -e 's/\\.[0-9a-z]*$$//'`; \
#	  inst=`echo $$inst | sed -e 's/^.*\///'`; \
#	  inst=`echo $$inst | sed '$(transform)'`.$$ext; \
#	  echo " rm -f '$(DESTDIR)$(mandir)/man$$ext/$$inst'"; \
#	  rm -f "$(DESTDIR)$(mandir)/man$$ext/$$inst"; \
#	done

# If modified smartd.conf exists install smartd.conf.sample instead
install-sysconfDATA: $(sysconf_DATA)
	$(MKDIR_P) '$(DESTDIR)$(sysconfdir)'
	@s="$(srcdir)/smartd.conf"; \
	f="$(DESTDIR)$(sysconfdir)/smartd.conf$(smartd_suffix)"; \
	if test -z "$(smartd_suffix)" && test -f "$$f"; then \
	  if cmp "$$s" "$$f" >/dev/null 2>/dev/null; then :; else \
	    echo "************************************************************"; \
	    echo "*** $$f preserved"; \
	    echo "*** installing smartd.conf.sample instead"; \
	    echo "************************************************************"; \
	    f="$$f".sample; \
	  fi; \
	fi; \
	echo " $(INSTALL_DATA) '$$s' '$$f'"; \
	$(INSTALL_DATA) "$$s" "$$f"

# If smartd.conf.sample exists preserve smartd.conf
uninstall-sysconfDATA:
	@f="$(DESTDIR)$(sysconfdir)/smartd.conf$(smartd_suffix)"; \
	if test -z "$(smartd_suffix)" && test -f "$$f".sample; then \
	  echo "************************************************************"; \
	  echo "*** $$f preserved"; \
	  echo "*** removing smartd.conf.sample instead"; \
	  echo "************************************************************"; \
	  f="$$f".sample; \
	fi; \
	echo " rm -f '$$f'"; \
	rm -f "$$f"

smartctl.o utility.o: svnversion.h

# Get version info from SVN
#svnversion.h: ChangeLog Makefile $(svn_deps)
#	@echo ' svn info | $$(VERSION_FROM_SVN_INFO) > $@'
#	@echo '/* svnversion.h.  Generated by Makefile from svn info.  */' > $@
#	@(cd $(srcdir) \
#	 && svnversion 2>/dev/null | sed -n 's,^\([0-9].*\),REV  "\1",p' \
#	 && TZ= LC_ALL=C svn info 2>/dev/null \
#	 | sed -n 'h;s,^.* Date: *\([^ ]*\) .*$$,DATE "\1",p;g;s,^.* Date: *[^ ]* *\([^ ]*\) .*$$,TIME "\1",p') \
#	| sed 's,^,#define SMARTMONTOOLS_SVN_,' >> $@

# SVN not available, guess version info from Id strings
svnversion.h: ChangeLog Makefile NEWS
	@echo ' cat ChangeLog NEWS $$(SOURCES) | $$(VERSION_FROM_SVN_IDS) > $@'
	@echo '/* svnversion.h.  Generated by Makefile from Id strings.  */' > $@
	@(cd $(srcdir) && cat ChangeLog NEWS Makefile.am configure.ac smart*.in *.cpp *.h) \
	| sed -n 's,^.*\$$[I][d]: [^ ]* \([0-9][0-9]* [0-9][-0-9]* [0-9][:0-9]*\)[^:0-9][^$$]*\$$.*$$,\1,p' \
	| sort -n -r \
	| sed -n 'h;s,^\([^ ]*\) .*$$,REV  "\1",p;g;s,^[^ ]* \([^ ]*\) .*$$,DATE "\1",p;g;s,^[^ ]* [^ ]* \([^ ]*\)$$,TIME "\1",p;q' \
	| sed 's,^,#define SMARTMONTOOLS_SVN_,' >> $@

update-smart-drivedb: update-smart-drivedb.in config.status
	$(SHELL) ./config.status --file=$@
	chmod +x $@

smartd_warning.sh: smartd_warning.sh.in config.status
	$(SHELL) ./config.status --file=$@
	chmod +x $@

##com.smartmontools.smartd.plist : os_darwin/com.smartmontools.smartd.plist.in
##	sed "s|/usr/sbin/|$(sbindir)/|" $< > $@

##install-initdDATA-darwin: $(initd_DATA)
##	$(MKDIR_P) '$(DESTDIR)$(initddir)'
##	$(INSTALL_DATA) $(top_builddir)/$(initd_DATA) $(DESTDIR)$(initddir)/$(initd_DATA)

##uninstall-initdDATA-darwin:
##	rm -f $(DESTDIR)$(initddir)/$(initd_DATA)

#$(initdfile): $(srcdir)/$(initdfile).in Makefile
#	sed 's|/usr/local/sbin/|$(sbindir)/|g' $(srcdir)/$(initdfile).in > $@

#install-initdDATA-generic: $(initd_DATA)
#	$(MKDIR_P) '$(DESTDIR)$(initddir)'
#	$(INSTALL_SCRIPT) '$(top_builddir)/$(initdfile)' '$(DESTDIR)$(initddir)/smartd$(smartd_suffix)'

#uninstall-initdDATA-generic:
#	rm -f '$(DESTDIR)$(initddir)/$(initd_install_name)'

install-initdDATA-null:
uninstall-initdDATA-null:

install-initdDATA : $(initd_DATA_install)

uninstall-initdDATA: $(initd_DATA_uninstall)

smartd.service: smartd.service.in Makefile
	@echo ' $$(SMARTD_SERVICE_FILTER) < $(srcdir)/smartd.service.in > $@'
	@{ \
	sed 's|/usr/local/sbin/smartd|$(sbindir)/smartd|' | \
	if test -n '$(SYSTEMD_LDADD)'; then \
	  cat; \
	else \
	  sed '/^Type=notify/d'; \
	fi | \
	if test -n '$(systemdenvfile)'; then \
	  sed 's|/usr/local/etc/sysconfig/smartmontools|$(systemdenvfile)|'; \
	else \
	  sed -e '/^EnvironmentFile=/d' -e 's| *\$$smartd[_a-z]* *||g'; \
	fi; } < $(srcdir)/smartd.service.in > $@

# Create empty directories if configured.
# Default install rules no longer create empty directories since automake 1.11.
installdirs-local:
	@for d in '$(smartdplugindir)' '$(savestatesdir)' '$(attributelogdir)'; do \
	  test -n "$$d" || continue; \
	  echo " $(MKDIR_P) '$(DESTDIR)$$d'"; \
	  $(MKDIR_P) "$(DESTDIR)$$d" || exit 1; \
	done

install-data-local: installdirs-local

# Implicit rule 'smart%: smart%.in ...' does not work with BSD make
smartctl.8: smartctl.8.in Makefile svnversion.h
	@echo ' $$(MAN_FILTER) < $(srcdir)/smartctl.8.in > $@'
	@$(MAN_FILTER) < $(srcdir)/smartctl.8.in > $@

smartd.8: smartd.8.in Makefile svnversion.h
	@echo ' $$(MAN_FILTER) < $(srcdir)/smartd.8.in > $@'
	@$(MAN_FILTER) < $(srcdir)/smartd.8.in > $@

smartd.conf.5: smartd.conf.5.in Makefile svnversion.h
	@echo ' $$(MAN_FILTER) < $(srcdir)/smartd.conf.5.in > $@'
	@$(MAN_FILTER) < $(srcdir)/smartd.conf.5.in > $@

update-smart-drivedb.8: update-smart-drivedb.8.in Makefile svnversion.h
	@echo ' $$(MAN_FILTER) < $(srcdir)/update-smart-drivedb.8.in > $@'
	@$(MAN_FILTER) < $(srcdir)/update-smart-drivedb.8.in > $@

smartctl.1m: smartctl.8
	@echo ' $$(SOLARIS_MAN_FILTER) < smartctl.8 > $@'
	@$(SOLARIS_MAN_FILTER) < smartctl.8 > $@

smartd.1m: smartd.8
	@echo ' $$(SOLARIS_MAN_FILTER) < smartd.8 > $@'
	@$(SOLARIS_MAN_FILTER) < smartd.8 > $@

smartd.conf.4: smartd.conf.5
	@echo ' $$(SOLARIS_MAN_FILTER) < smartd.conf.5 > $@'
	@$(SOLARIS_MAN_FILTER) < smartd.conf.5 > $@

update-smart-drivedb.1m: update-smart-drivedb.8
	@echo ' $$(SOLARIS_MAN_FILTER) < update-smart-drivedb.8 > $@'
	@$(SOLARIS_MAN_FILTER) < update-smart-drivedb.8 > $@

htmlman: smartctl.8.html smartd.8.html smartd.conf.5.html update-smart-drivedb.8.html

pdfman:  smartctl.8.pdf smartd.8.pdf smartd.conf.5.pdf update-smart-drivedb.8.pdf

txtman:  smartctl.8.txt smartd.8.txt smartd.conf.5.txt update-smart-drivedb.8.txt

%.5.html: %.5
	$(MAN2HTML) $< > $@.tmp
	@echo ' $$(FIXHTML) < $@.tmp > $@'
	@$(FIXHTML) < $@.tmp > $@

%.8.html: %.8
	$(MAN2HTML) $< > $@.tmp
	@echo ' $$(FIXHTML) < $@.tmp > $@'
	@$(FIXHTML) < $@.tmp > $@

%.5.pdf: %.5
	$(MAN2PDF) $< > $@

%.8.pdf: %.8
	$(MAN2PDF) $< > $@

%.5.txt: %.5
	$(MAN2TXT) $< > $@

%.8.txt: %.8
	$(MAN2TXT) $< > $@

# Check drive database syntax
check:
	@if ./smartctl -B $(srcdir)/drivedb.h -P showall >/dev/null; then \
	  echo "$(srcdir)/drivedb.h: OK"; \
	else \
	  echo "$(srcdir)/drivedb.h: Syntax check failed"; exit 1; \
	fi

# Create cppcheck report
cppcheck: cppcheck.txt
cppcheck.txt: $(smartctl_SOURCES) $(EXTRA_smartctl_SOURCES) \
              $(smartd_SOURCES) $(EXTRA_smartd_SOURCES)
	$(srcdir)/cppcheck.sh $(CPPCHECKFLAGS) > $@

# Windows resources

smartctl_res.o: smartctl_res.rc $(os_win32_manifest)
	$(WINDRES) $< $@

smartd_res.o: smartd_res.rc syslogevt.rc $(os_win32_manifest)
	$(WINDRES) $< $@

runcmda_res.o: runcmda_res.rc defadmin.manifest
	$(WINDRES) $< $@

runcmdu_res.o: runcmdu_res.rc $(os_win32_manifest)
	$(WINDRES) $< $@

wtssendmsg_res.o: wtssendmsg_res.rc $(os_win32_manifest)
	$(WINDRES) $< $@

smartctl_res.rc: os_win32/versioninfo.rc.in Makefile svnversion.h
	@n=smartctl d="Control and Monitor Utility for SMART Disks"; $(WIN_MAKE_RES)
	@$(WIN_APP_MANIFEST)

smartd_res.rc: os_win32/versioninfo.rc.in Makefile svnversion.h
	@n=smartd d="SMART Disk Monitoring Daemon"; $(WIN_MAKE_RES)
	echo '#include "./syslogevt.rc"' >> $@
	@$(WIN_APP_MANIFEST)

runcmdu_res.rc: os_win32/versioninfo.rc.in Makefile svnversion.h
	@n=runcmdu d="Run console command"; $(WIN_MAKE_RES)
	@$(WIN_APP_MANIFEST)

runcmda_res.rc: os_win32/versioninfo.rc.in Makefile svnversion.h
	@n=runcmda d="Run console command as admin"; $(WIN_MAKE_RES)
	echo '1 24 "./defadmin.manifest"' >> $@

wtssendmsg_res.rc: os_win32/versioninfo.rc.in Makefile svnversion.h
	@n=wtssendmsg d="Send console messages"; $(WIN_MAKE_RES)
	@$(WIN_APP_MANIFEST)

syslogevt.rc: os_win32/syslogevt.mc
	$(WINDMC) -b $<

defadmin.manifest: os_win32/default.manifest
	sed 's,"asInvoker","requireAdministrator",' $< > $@

# Build Windows distribution

dist-win32: $(distzip_win32)

install-win32: $(distinst_win32)
	./$(distinst_win32)

installer-win32: $(distinst_win32)

distdir-win32: distdir.mkdir $(FILES_WIN32)

$(distzip_win32): distdir.mkdir $(FILES_WIN32)
	@rm -fv $(distzip_win32)
	cd $(distdir_win32) && zip -9 ../$(distzip_win32) bin/* doc/*
	md5sum $@ > $@.md5
	sha1sum $@ > $@.sha1
	sha256sum $@ > $@.sha256

# Build NSIS installer
# Note: Only option character '-' is also compatible with Linux version of makensis
#$(distinst_win32): os_win32/installer.nsi smartctl_res.rc distdir.mkdir $(FILES_WIN32)
#	test -z '$(builddir_win64)' || ( cd $(builddir_win64) && make distdir-win32 )
#	@date=`sed -n 's,^.*DATE[^"]*"\([^"]*\)".*$$,\1,p' svnversion.h` && \
#	rev=`sed -n 's,^.*REV[^"]*"\([^"]*\)".*$$,r\1,p' svnversion.h` && \
#	version=`sed -n 's|^ *VALUE "FileVersion", "\([0-9.]*\)".*$$|\1|p' smartctl_res.rc` && \
#	yy=`echo "$$date" | sed -n 's,^20\([0-9][0-9]\).*$$,\1,p'`; yy="$${yy:-XX}" && \
#	verstr="$(PACKAGE_VERSION) $$date $$rev "$(BUILD_INFO) && \
#	d64= && if [ -n '$(builddir_win64)' ]; then d64='-DINPDIR64=$(builddir_win64)/$(PACKAGE)-$(VERSION).win64'; fi && \
#	echo "'$(MAKENSIS)' -V2 -NOCD -DINPDIR=$(distdir_win32) $$d64 -DOUTFILE=$@ -DVERSION=$$version -DYY=$$yy -DVERSTR='$$verstr' $<" && \
#	'$(MAKENSIS)' -V2 -NOCD -DINPDIR=$(distdir_win32) $$d64 -DOUTFILE=$@ -DVERSION=$$version -DYY=$$yy -DVERSTR="$$verstr" $<
#	md5sum $@ > $@.md5
#	sha1sum $@ > $@.sha1
#	sha256sum $@ > $@.sha256

# Build drivedb.h update tool
#update-smart-drivedb.exe: os_win32/update-smart-drivedb.nsi
#	"$(MAKENSIS)" -V2 -NOCD -DBRANCH=$(DRIVEDB_BRANCH) $<

$(distinst_win32):
	@echo "makensis: command not found. Please install NSIS from http://nsis.sourceforge.net/" 1>&2
	@exit 1

cleandist-win32:
	rm -rf $(distdir_win32) distdir.mkdir

distdir.mkdir:
	@test -d $(exedir_win32) || mkdir -pv $(exedir_win32)
	@test -d $(docdir_win32) || mkdir -pv $(docdir_win32)
	touch $@

$(exedir_win32)/%.exe: %.exe
	cp -p $< $@
	if test -n '$(STRIP)'; then $(STRIP) -s $@; else strip -s $@; fi
	touch -r $< $@

# strip would break NSIS integrity check
$(exedir_win32)/update-smart-drivedb.exe: update-smart-drivedb.exe
	cp -p $< $@

$(exedir_win32)/%.h: $(srcdir)/%.h
	$(UNIX2DOS) < $< > $@
	touch -r $< $@

$(exedir_win32)/%.cmd: $(srcdir)/os_win32/%.cmd
	$(UNIX2DOS) < $< > $@
	touch -r $< $@

$(exedir_win32)/%.ps1: $(srcdir)/os_win32/%.ps1
	$(UNIX2DOS) < $< > $@
	touch -r $< $@

$(docdir_win32)/%.html: %.html
	$(UNIX2DOS) < $< > $@
	touch -r $< $@

$(docdir_win32)/%.pdf: %.pdf
	cp -p $< $@

$(docdir_win32)/%.txt: $(srcdir)/%
	$(UNIX2DOS) < $< > $@
	touch -r $< $@

$(docdir_win32)/%.conf: $(srcdir)/%.conf
	$(UNIX2DOS) < $< > $@
	touch -r $< $@

$(docdir_win32)/checksums$(win_bits).txt: $(EXEFILES_WIN32)
	(cd $(exedir_win32) && md5sum *.exe && sha1sum *.exe && sha256sum *.exe) \
	| $(UNIX2DOS) > $@

# Build non-console version of smartctl for GSmartControl.
# The script below changes the word at offset 220 (Subsystem) from 3
# (Console) to 2 (GUI) in a copy of smartctl.exe.
# This will be changed when a tool (like 'editbin') is available in
# the Cygwin distribution
smartctl-nc.exe: smartctl.exe
	@rm -f $@
	cp -p smartctl.exe $@.tmp
	@if test `od -A n -j 220 -N 2 -d $@.tmp` -eq 3; then :; \
	  else echo "invalid EXE header"; exit 1; fi
	@echo "editbin /subsystem:windows $@.tmp"
	@echo -ne '\002' | dd bs=1 seek=220 count=1 conv=notrunc of=$@.tmp 2>/dev/null
	@if test `od -A n -j 220 -N 2 -d $@.tmp` -eq 2; then :; \
	  else echo "EXE patch failed"; exit 1; fi
	mv -f $@.tmp $@

# Build runcmd?.exe and wtssendmsg.exe
runcmd.o: os_win32/runcmd.c
	$(CC) -c -Os $<

runcmdu.exe: runcmd.o runcmdu_res.o
	$(CC) -o $@ $^

runcmda.exe: runcmd.o runcmda_res.o
	$(CC) -o $@ $^

wtssendmsg.exe: os_win32/wtssendmsg.c wtssendmsg_res.o
	$(CC) -Os -o $@ $^ -lwtsapi32

config-vc$(vcver): $(CONFIG_VC_FILES)

$(srcdir)/os_win32/vc$(vcver)/config.h: config.h Makefile
	sed -e '1i/* os_win32/vc$(vcver)/config.h.  Generated from config.h by Makefile.  */' \
	    -e 's,^#define HAVE_\(ATTR_PACKED\|GETTIMEOFDAY\|LONG_DOUBLE_WIDER\|STRINGS_H\|UNISTD_H\) 1$$,/* #undef HAVE_\1 */ /* VC$(vcver) */,' \
	    -e 's,^\(#define SMARTMONTOOLS_BUILD_HOST "[^-]*\)[^"]*,\1-pc-w32vc$(vcver),' $< > $@

$(srcdir)/os_win32/vc$(vcver)/svnversion.h: svnversion.h
	cp $< $@

$(srcdir)/os_win32/vc$(vcver)/smartctl_res.rc: smartctl_res.rc
	sed '/^1 24 /d' $< > $@

$(srcdir)/os_win32/vc$(vcver)/smartd_res.rc: smartd_res.rc
	sed '/^1 24 /d' $< > $@

clean-vc$(vcver):
	rm -f $(srcdir)/os_win32/vc$(vcver)/smartmontools.VC.VC.opendb
	rm -f $(srcdir)/os_win32/vc$(vcver)/smartmontools.VC.db
	rm -f $(srcdir)/os_win32/vc$(vcver)/syslogevt.h
	rm -rf $(srcdir)/os_win32/vc$(vcver)/Debug
	rm -rf $(srcdir)/os_win32/vc$(vcver)/Release
	rm -rf $(srcdir)/os_win32/vc$(vcver)/x64

distclean-vc$(vcver): clean-vc$(vcver)
	rm -f $(CONFIG_VC_FILES)

maintainer-clean-vc$(vcver): distclean-vc$(vcver)
	rm -rf $(srcdir)/os_win32/vc$(vcver)/.vs

# build darwin installer 
#$(pkg_darwin):
#	${MAKE} install DESTDIR=$(distdir_darwin)/root
#	@cp $(srcdir)/os_darwin/pkg/root/usr/local/sbin/smart-pkg-uninstall $(distdir_darwin)/root$(sbindir)
#	@mkdir -p $(distdir_darwin)/pkg
#	@( cd $(distdir_darwin)/root && find . | cpio -o --format odc --owner 0:80 | gzip -c ) > $(distdir_darwin)/pkg/Payload
#	PAYLOAD_FILES=`find $(distdir_darwin)/root | wc -l` &&\
#	PAYLOAD_SIZEKB=`du -BK  -s $(distdir_darwin)/root|${AWK} '{print $$1}'|tr -d 'K'` &&\
#	sed -e "s|@version@|$(VERSION)|" -e "s|@files@|$${PAYLOAD_FILES}|" \
#		-e "s|@size@|$${PAYLOAD_SIZEKB}|" $(srcdir)/os_darwin/pkg/PackageInfo.in \
#		> $(distdir_darwin)/pkg/PackageInfo &&\
#	sed -e "s|@version@|$(VERSION)|" -e "s|@files@|$${PAYLOAD_FILES}|" -e "s|@size@|$${PAYLOAD_SIZEKB}|" \
#		-e "s|@pkgname@|$(pkg_darwin)|" \
#		$(srcdir)/os_darwin/pkg/Distribution.in > $(distdir_darwin)/pkg/Distribution
#	@mkdir -p $(distdir_darwin)/pkg/Resources/English.lproj
#	@cp $(srcdir)/COPYING $(distdir_darwin)/pkg/Resources/English.lproj/license.txt
#	@mkbom -u 0 -g 80 $(distdir_darwin)/root $(distdir_darwin)/pkg/Bom
#	@mkdir -p $(distdir_darwin)/dmg
#	@( cd $(distdir_darwin)/pkg && xar --compression none -cf "../dmg/$(pkg_darwin)" * )

# build darwon dmg image
#$(dmg_darwin):
#	@cp $(srcdir)/os_darwin/pkg/installer/README.html $(distdir_darwin)/dmg
#	@mkisofs -V 'smartmontools' -no-pad -r -apple -o $(distdir_darwin)/smartmontools-$(VERSION).iso \
#		-hfs-bless "$(distdir_darwin)/dmg/" "$(distdir_darwin)/dmg/"
#	@dmg dmg $(distdir_darwin)/smartmontools-$(VERSION).iso $(dmg_darwin)
#	md5sum $@ > $@.md5
#	sha1sum $@ > $@.sha1
#	sha256sum $@ > $@.sha256

#install-darwin: install-darwin-cleanup $(pkg_darwin) $(dmg_darwin)

#install-darwin-cleanup: 
#	@rm -rf $(distdir_darwin)

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
